### ISSUE TITLE
JS Call macro?

### ISSUE THREAD

**Issue by Telmtone** [JunoLab/Blink.jl#10]
Hi,

I saw in @one-more-minute 2015 Juliacon presentation the use of a macro to call JS. Is this macro available in this package? Also, can it be used to call and or wrap JS charting libraries without have to write JS?

Thanks

**Comment by EricForgy** [comment]
Hi @Telmtone ,

Since Blink.jl now supports this (super cool) macro, do you want to close this issue?

To answer your other question, yes. Have a look at some of things we're doing with [Plotly.js](https://github.com/plotly/Plotly.jl/issues/18).

Best regards,
Eric
