### ISSUE TITLE
Cannot paste into text input fields.

### ISSUE THREAD

**Issue by NHDaly** [JunoLab/Blink.jl#101]
When I try to copy/paste into a text input field, it always pastes nothing. If I select text and paste over it, it just clears the selected text out.

This is true no matter whether I use Edit->paste or <kbd>⌘</kbd><kbd>v</kbd>.

I am on Mac 10.12.6 (16G1036), using `julia v0.6.1`.

This happens even for the simplest forms:
``` julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Blink

julia> w = Window() ; body!(w, "<form> <input type=text/> </form>");
```
I cannot paste into the form. The same is true for the developer tools; I also cannot paste into the developer Console.

Also, for what it's worth, updating to a newer electron didn't change this behavior. (neither `1.6.15` from #97, nor when I manually updated it again to the even newer `1.7.10`)

------------------------------------

However, interestingly, it works no problem when I use `Blink` from within Atom. I ran those same commands in the Atom (Juno) console, and pasting works just fine:

![screen shot 2017-12-23 at 4 10 44 pm](https://user-images.githubusercontent.com/1582097/34322678-ee7666d0-e7fb-11e7-96e0-859538b5ab08.png)

I assume that when running from inside Atom, blink must be defaulting to the same version of Electron that Atom ships with? I think that because it doesn't open a new _application_ for the `Window`, it just opens another window within the Atom application.

Does pasting work for others?

**Comment by pfitzseb** [comment]
Seems to be an electron issue: https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by NHDaly** [comment]
Awesome find, thanks for the pointer.

I've done a bit of digging around with this, but wasn't able to get anything to work. Reading the [documentation for Menu](https://github.com/electron/electron/blob/master/docs/api/menu.md), it looks like `require("menu")` must be called from the ["main process"](https://github.com/electron/electron/blob/master/docs/glossary.md#main-process).

I tried just running `require("menu")` from the Developer Tools console, but predictably it had an `Uncaught Error: Cannot find module 'menu'`.

So then I tried (https://github.com/NHDaly/Blink.jl/commit/e1facd9) adding the `var Menu = require("menu");` line to the top of [main.js](https://github.com/JunoLab/Blink.jl/blob/master/src/AtomShell/main.js), after the other requires, and that also failed. When I create a new Window, I get the following pop-up message:

> ### A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module 'menu'
>     at Module._resolveFilename (module.js:470:15)
>     at Function.Module._resolveFilename (/Users/daly/.julia/v0.6/Blink/deps/Julia.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/daly/.julia/v0.6/Blink/src/AtomShell/main.js:3:12)
>     at Object.<anonymous> (/Users/daly/.julia/v0.6/Blink/src/AtomShell/main.js:135:3)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)

Which was surprising, since it even says right there it's in the main process. So is the problem that somehow we don't have the menu module installed? It looks like the "process Main" line of the documentation [was written for `v1.4.6`](https://github.com/electron/electron/commit/ac68de62154cd4f38ac060e55098b8a6725e8857), so we should be okay (my electron is `v1.6.15` after #97).

Is there a set of installed modules that our version of Electron ships with, which doesn't include `menu`?
Thanks! :)

**Comment by NHDaly** [comment]
Okay, just kidding, I just didn't follow the docs very well.

`var Menu = require("menu");` should have been `const {app, Menu, BrowserWindow} = require('electron')`.
Thanks! :)

**Comment by NHDaly** [comment]
Although actually, huh... Now that I'm looking at this, copy/paste *does* work okay after a clean install, checkout to master, and `Blink.AtomShell.install()`.

So I don't know why I even made the initial post... I'm going to tentatively close this for now. Feel free to reopen this if you/anyone else has trouble pasting? Haha sorry and thanks!
