### ISSUE TITLE
Pkg.build("Blink") failure

### ISSUE THREAD

**Issue by carlobaldassi** [JunoLab/Blink.jl#118]
On Julia 0.6, when doing `Pkg.build("Blink")` I got a failure with a "Blink not defined" message. The error is triggered by [this line in deps/build.jl](https://github.com/JunoLab/Blink.jl/blob/8208e510e328715d8939a85ef124e5089c436ece/deps/build.jl#L14). It seems that adding `using Blink` at the start of the module fixes the issue.

**Comment by sglyon** [comment]
Ahh yes you are totally right. Sorry, this is my fault 

We should delete the `Blink.`  altogether. The include statement at the top of the module defines the `AtomShell` module

**Comment by dsweber2** [comment]
I also had this error, and had no problems after just removing `Blink.AtomShell` and calling `install` as you say.

**Comment by sglyon** [comment]
Great! I'll make a quick PR to fix the issue

**Comment by sglyon** [comment]
Yikes! I accidentally committed to master -- @carlobaldassi, if you are able will you please `Pkg.checkout("Blink")` and test it out?
