### ISSUE TITLE
Windows: MethodError: `init` has no method matching init()

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#12]
After adding Blink.jl and following the first example, I get the following:

    julia> using Blink
    
    julia> a = Blink.init()
    ERROR: MethodError: `init` has no method matching init()

Here is my Blink.jl version:

    julia> Pkg.installed()["Blink"]
    v"0.1.4+"

and here is my:

    julia> versioninfo()
    Julia Version 0.4.0
    Commit 0ff703b* (2015-10-08 06:20 UTC)
    Platform Info:
      System: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

Any ideas?

Edit: Also, when I try to debug, this is what I get:

    julia> Blink.init(debug = true)
    ERROR: ArgumentError: function init does not accept keyword arguments

**Comment by EricForgy** [comment]
I'm guessing this is because I do not have Node.js installed? :)

If I get this working, I'll try to submit a PR on the docs.

**Comment by rohitvarkey** [comment]
Are you on `Blink` master? The latest version does not seem to define `init()`. I think if you run `Pkg.free("Blink")` you should get back a working version.

**Comment by EricForgy** [comment]
Thanks Rohit. Yeah, I think I tried it using Pkg.add and it didn't work, so tried master and still couldn't get it to work. If master does not define "init", what is an equivalent way to run the samples from the README?

**Comment by rohitvarkey** [comment]
@one-more-minute seems to have factored out the functionality from the README to [DevTools](https://github.com/JunoLab/DevTools.jl) (This has the BlinkDisplay module) and [Media](https://github.com/JunoLab/Media.jl) (This has the display system). I think you'll need to be on master of DevTools and Blink for it to work nicely.

If you are looking to do things like just display stuff on a Blink window, DevTools and Media will be enough.

For example,
```julia
using DevTools, Gadfly
plot(...) #Will open in Blink Window
using Media
setdisplay(Media.Tabular, BlinkDisplay._display)
rand(5, 5) #Will open in a Blink Window
```
