### ISSUE TITLE
Outline of the plan for Blink, DevTools

### ISSUE THREAD

**Issue by rohitvarkey** [JunoLab/Blink.jl#13]
I was trying to get `Blink` to run when I noticed that on master, there has been quite a lot of changes with a lot of factoring out of things like `BlinkDisplay` to `DevTools.jl`.

I read about how Blink allows the user to fire up different windows to do plots in using BlinkDisplay and was hoping I could tie into this system to get [ThreeJS.jl](https://github.com/rohitvarkey/ThreeJS.jl) to work from the Julia REPL. I'm a bit confused as to what package I should use to try and develop that feature now that `BlinkDisplay` has gone over to `DevTools`.

It would be great if you could put up an outline of your plans with these packages so that others can plan their development plans accordingly! :smile:

cc: @one-more-minute

**Comment by rohitvarkey** [comment]
After messing around with the packages, I've drawn the following conclusions. 

1. Blink will now be focused on just the atom-shell part and drawing windows, communicating to them etc.
2. Media will be the package that decides the display system.
3. DevTools will provide the higher level API, providing functionality like the BlinkDisplay module.

Please correct me if I misunderstood something! Will close this now.

**Comment by one-more-minute** [comment]
Yep, I think you got it! Sorry for taking a while to get back but yeah, that's the plan in a nutshell.

**Comment by yeison** [comment]
At the moment, trying to follow the README.  When I do the following

```Pkg.clone("https://github.com/JunoLab/DevTools.jl")
```using DevTools

**Comment by yeison** [comment]
I suppose my assumption was wrong.  I got this error:

```julia
Error showing value of type Gadfly.Plot:
ERROR: MethodError: `render` has no method matching render(::Blink.AtomShell.Window, ::Gadfly.Plot)
Closest candidates are:
  render(::Media.NoDisplay, ::Any)
  render(::Any)
```

**Comment by yeison** [comment]
Okay, I created a new workspace and now I see the missing variables so scratch my comments.
