### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by tkoolen** [JunoLab/Blink.jl#131]
I'd really appreciate a tag that includes https://github.com/JunoLab/Blink.jl/pull/119. Thanks!

**Comment by pfitzseb** [comment]
Do you have an opinion on https://github.com/JunoLab/Blink.jl/pull/127? I'd like to get that merged before tagging the next version.

**Comment by tkoolen** [comment]
Is https://github.com/JunoLab/Blink.jl/pull/127 not happening? Anyway, could you just tag a new release at current master?

**Comment by pfitzseb** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16094

**Comment by tkoolen** [comment]
Thanks!
