### ISSUE TITLE
Error building `Blink`on 1.0.0

### ISSUE THREAD

**Issue by mgiugliano** [JunoLab/Blink.jl#141]
Error: Error building `Blink`:
│ ERROR: LoadError: LoadError: LoadError: UndefVarError: is_apple not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] eval at ./boot.jl:319 [inlined]
│  [3] @static(::LineNumberNode, ::Module, ::Any) at ./osutils.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include at ./sysimg.jl:29 [inlined]
│  [7] include(::String) at /Users/XXX/.julia/packages/Blink/uzZJ3/deps/build.jl:1
│  [8] top-level scope at none:0
│  [9] include at ./boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at ./loading.jl:1038
│  [11] include(::Module, ::String) at ./sysimg.jl:29
│  [12] include(::String) at ./client.jl:388
│  [13] top-level scope at none:0
│ in expression starting at /Users/XXX/.julia/packages/Blink/uzZJ3/src/AtomShell/install.jl:9
│ in expression starting at /Users/XXX/.julia/packages/Blink/uzZJ3/src/AtomShell/install.jl:9
│ in expression starting at /Users/XXX/.julia/packages/Blink/uzZJ3/deps/build.jl:4
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by pfitzseb** [comment]
Blink.jl doesn't work on Julia 1.0 yet, see e.g. #139 for progress.
