### ISSUE TITLE
What to do about quit(::ElectronShell)?

### ISSUE THREAD

**Issue by tkoolen** [JunoLab/Blink.jl#142]
Blink has:

https://github.com/JunoLab/Blink.jl/blob/3eff4999627968c979a7526de7cc218aa39e6755/src/AtomShell/process.jl#L107

where `quit` is imported from `Base`. `quit` is deprecated in 0.7 (now `exit`). Arguably, `Base.quit` shouldn't have been extended in the first place, so I don't think it should be replaced with an overload of `Base.exit` now. Should `AtomShell.quit` just not be exported?

**Comment by pfitzseb** [comment]
That seems sensible to me, yes.

**Comment by NHDaly** [comment]
To me too, fwiw
