### ISSUE TITLE
Blink not building on Julia 1.0

### ISSUE THREAD

**Issue by piovac** [JunoLab/Blink.jl#145]
`Blink.jl` is not building in `Julia 1.0`. The reason is due to previously deprecated functions and statement that are not more supported in `Julia 1.0`. The affected files are: `deps\build.jl`, `src\AtomShell\install.jl`, `src\AtomShell\process.jl`, `src\AtomShell\window.jl`. The functions `is_apple()`, `is_windows()`, `is_unix()`, `is_linux()` need to be substituted with `Sys.isapple()`, `Sys.iswindows()`, `Sys.isunix()`, `Sys.islinux()`respectively. The declaration `const` needs to be deleted.

**Comment by rdeits** [comment]
Thank you for reporting. This is currently being worked on in https://github.com/JunoLab/Blink.jl/pull/143

**Comment by piovac** [comment]
Please note that `JuliaWeb/HttpParser.jl` package (which I think it's one of your dependency) has similar issues as described in [#89](https://github.com/JuliaWeb/HttpParser.jl/issues/89).

**Comment by rdeits** [comment]
That dependency is also removed in #143
