### ISSUE TITLE
Build error on julia 1.0

### ISSUE THREAD

**Issue by adhal007** [JunoLab/Blink.jl#149]
![screenshot from 2018-08-23 01-57-17](https://user-images.githubusercontent.com/34755237/44515831-61afd600-a678-11e8-8c8e-f51913c0fb45.png)

**Comment by rdeits** [comment]
Please do not post screenshots of code: just copy-and-paste the error message. For some good reasons why, please see: https://meta.stackoverflow.com/a/285557/641846

Also, this appears to be an Interact.jl issue, not a Blink.jl issue. You will need Interact v0.9.0 or higher for Julia 1.0.
