### ISSUE TITLE
could not import Base.quit into AtomShell

### ISSUE THREAD

**Issue by hajsf** [JunoLab/Blink.jl#153]
I use MacBook Air, and got the below while running `using Blink`

> julia> using Blink
> [ Info: Recompiling stale cache file /Users/hasan/.julia/compiled/v1.0/Blink/wSmkt.ji for Blink [ad839575-38b3-5650-b840-f874b8c74a25]
> WARNING: could not import Base.quit into AtomShell

**Comment by rdeits** [comment]
This is safe for you to ignore, but it's still something we should fix. See also: https://github.com/JunoLab/Blink.jl/issues/142
