### ISSUE TITLE
How To Open Electron DevTools?

### ISSUE THREAD

**Issue by travigd** [JunoLab/Blink.jl#159]
I'm sorry if I'm missing something but I can't seem to find any way to open DevTools (the Chrome inspector tools, not the Julia package). The Cmd + Something + I apparently _used_ to work on a Mac but only from a Mac and has been recently removed. Is there any way to (programmatically or otherwise) open DevTools for the window?

**Comment by piever** [comment]
`opentools(w)` where `w` is your window.

**Comment by travigd** [comment]
Thanks! Feel free to close the issue, or I suppose leave it open if you want it to become a "opentools is undocumented" issue.

**Comment by NHDaly** [comment]
> but only from a Mac and has been recently removed

Huh, this still works for me, fwiw. It's <kbd>cmd</kbd><kbd>option</kbd><kbd>i</kbd>. I didn't know that only worked on a mac though.. I guess this would be an Electron issue, not a Blink issue, but that's a bummer if it's been removed.

**Comment by NHDaly** [comment]
Closed by #163

**Comment by NHDaly** [comment]
>  I suppose leave it open if you want it to become a "opentools is undocumented" issue.

Thanks for the kick in the butt! :)
