### ISSUE TITLE
Error on closing a Blink window

### ISSUE THREAD

**Issue by ViralBShah** [JunoLab/Blink.jl#17]
I just tried Gadfly and Plotlyjs with Blink, and I finally have something I have wanted for the longest time! Working in the terminal REPL and having a dedicated plain plot window that can pop up when I plot in the REPL. Great work!

When I close a Blink window on OS X, I get:

````
julia> Error handling websocket connection:
ArgumentError: stream is closed or unusable
 in check_open at /Users/viral/Desktop/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in uv_write at stream.jl:930
 in flush at stream.jl:979
 in locked_write at /Users/viral/.julia/v0.4/WebSockets/src/WebSockets.jl:142
 in handle_control_frame at /Users/viral/.julia/v0.4/WebSockets/src/WebSockets.jl:248
 in read at /Users/viral/.julia/v0.4/WebSockets/src/WebSockets.jl:315
 in ws_handler at /Users/viral/.julia/v0.4/Blink/src/content/server.jl:43
 in splitquery at /Users/viral/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/viral/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/viral/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/viral/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/viral/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/viral/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/viral/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/viral/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/viral/.julia/v0.4/WebSockets/src/WebSockets.jl:382
 in on_message_complete at /Users/viral/.julia/v0.4/HttpServer/src/HttpServer.jl:393
 in on_message_complete at /Users/viral/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/viral/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/viral/.julia/v0.4/HttpServer/src/HttpServer.jl:365
 in anonymous at task.jl:447
````

**Comment by spencerlyon2** [comment]
I've noticed this too and it can be annoying.

I have a local patch for this that fixes the problem at this point in the callback:

```
 in ws_handler at /Users/viral/.julia/v0.4/Blink/src/content/server.jl:43
```

But that just pushes the error further up the list and we still see it in the WebSockets.jl functions.

@one-more-minute any ideas?

**Comment by one-more-minute** [comment]
Fixed (if you can call it that) with https://github.com/JunoLab/Blink.jl/commit/81a049f77c094fec514eb4a2c700460446127fd7. @spencerlyon2 presumably you fixed the error type and then saw the same error I get when removing the `yield`?

I think the deeper problem is that the basic Julian pattern for working with streams is broken:
```julia
while isopen(socket)
  read(socket)
end
```
This looks OK at first glance, but it's brittle because `read` blocks – if the socket closes in the mean time you get an error.

One way to solve this could look like:
```julia
while true
  wait_for_something_to_happen(socket) # this blocks
  if hasdata(socket) # non blocking
    read(socket)
  elseif isclosed(socket)
    ...
  end
end
```
It's not particularly elegant, though. Perhaps something more like:
```julia
@select begin
  onread(socket) => ...
  onclose(socket) => ...
end
```
Functions like `onread`, `onreadline` etc. could return promises to be selected on. You'd have to figure out how to prioritise the `onclose` event over the read error, though.

For Blink's purposes we can get away with the brittle error-catching code, but in general I think this is an important problem in the current state of Julia.

**Comment by one-more-minute** [comment]
If we don't mind having exceptions as part of the API, something like:
```julia
try
  read(socket)
catch e
  if isa(e, CloseError) && e.obj == socket
    # handle error
  else
    rethrow()
  end
end
```
would be a thousand time more robust than what we currently have. It's also really verbose, though, and we've managed to avoid relying on exceptions so far.

**Comment by spencerlyon2** [comment]
@one-more-minute yep, I changed the error type, but didn't adjust `return -> yeild()`. Good call.

And yeah, I think that a solid api redesign would be great.

**Comment by ViralBShah** [comment]
Thanks. Confirming that this is fixed on the master of Blink.

**Comment by EricForgy** [comment]
> For Blink's purposes we can get away with the brittle error-catching code, but in general I think this is an important problem in the current state of Julia.

Yeah. I recently submitted a [PR to HttpServer](https://github.com/JuliaWeb/HttpServer.jl/pull/84) for similar reasons.
