### ISSUE TITLE
Automatically install AtomShell

### ISSUE THREAD

**Issue by sebastianpech** [JunoLab/Blink.jl#170]
This is just a general question about the installation of the AtomShell. I'm using Blink in a package of mine and was thinking about adding AtomShell installation as a build step or in the `__init__()` function.
What is the reasoning for not doing this automatically?

**Comment by pfitzseb** [comment]
If you're using Blink inside of Juno for example we can reuse the electron version shipped with Atom. I'm not super convinced of that reasoning anymore though :)

**Comment by pfitzseb** [comment]
`AtomShell.isinstalled()` only returns true if Electron has been installed by Blink, IIRC, so that wouldn't be super helpful. I do think that we should download the Electron binaries by default though.

**Comment by rdeits** [comment]
Yeah, it would make my life a bit easier if Blink installed AtomShell by default. As an example, it would mean that RigidBodySim.jl would no longer need a fake `Pkg.build` step just to install AtomShell: https://github.com/JuliaRobotics/RigidBodySim.jl/blob/master/deps/build.jl

**Comment by NHDaly** [comment]
Okay, i'm making it happen!

Please voice your objections on #176 otherwise I say let's pull the trigger!
