### ISSUE TITLE
how to install electron by manually download

### ISSUE THREAD

**Issue by cailiangliang765** [JunoLab/Blink.jl#180]
https://github.com/JunoLab/Blink.jl/blob/748abe2da9021585d6d8d8bd7b7cfcb5fda0bf2c/src/AtomShell/install.jl#L52-L58
how to install electron by manually download. my net was slow inside the julia. i try to fix this file as 
`if Sys.islinux()
  arch = Int == Int64 ? "x64" : "ia32"
  file = "~/.julia/packages/Blink/6QR5U/deps/electron-v2.0.5-linux-x64.zip"
  run(`unzip -q $file -d atom`)
  rm(file)
end`
but it still download by internet.

**Comment by NHDaly** [comment]
Hmm, i'm not sure. I think you can also just unzip it manually as well, outside of julia if you really wanted to.

As long as there ends up being a directory called `atom` in there, it should count as being installed:
https://github.com/JunoLab/Blink.jl/blob/748abe2da9021585d6d8d8bd7b7cfcb5fda0bf2c/src/AtomShell/install.jl#L15-L17

-----

What are the steps you are doing that cause it to re-download?

**Comment by cailiangliang765** [comment]
> Hmm, i'm not sure. I think you can also just unzip it manually as well, outside of julia if you really wanted to.
> 
> As long as there ends up being a directory called `atom` in there, it should count as being installed:
> [Blink.jl/src/AtomShell/install.jl](https://github.com/JunoLab/Blink.jl/blob/748abe2da9021585d6d8d8bd7b7cfcb5fda0bf2c/src/AtomShell/install.jl#L15-L17)
> 
> Lines 15 to 17 in [748abe2](/JunoLab/Blink.jl/commit/748abe2da9021585d6d8d8bd7b7cfcb5fda0bf2c)
> 
>  isinstalled() = Sys.isapple() ? 
>      isfile(joinpath(folder(), "version")) : 
>      isdir(joinpath(folder(), "atom")) 
> What are the steps you are doing that cause it to re-download?

thanks for your reply. i find the electron-v2.0.5-linux-x64.zip file was uncompletly download. i solve this by re-download it. this work for me.

**Comment by NHDaly** [comment]
Great, i'm glad! :)
