### ISSUE TITLE
ERROR: could not spawn `/home/miki/.julia/v0.4/Blink/deps/atom/atom /home/miki/.julia/v0.4/Blink/src/AtomShell/main.js port 7072`: no such file or directory (ENOENT)

### ISSUE THREAD

**Issue by ackalker** [JunoLab/Blink.jl#19]
After installing Blink package, I'm getting the following errors when following the example in `README.md`:
```julia
julia> using Blink

julia> w = Window(a) # typo? a isn't defined yet.
ERROR: UndefVarError: a not defined

julia> w = Window()
ERROR: could not spawn `/home/miki/.julia/v0.4/Blink/deps/atom/atom /home/miki/.julia/v0.4/Blink/src/AtomShell/main.js port 7072`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
 in anonymous at process.jl:415
 in setup_stdio at process.jl:403
 in spawn at process.jl:414
 in init at /home/miki/.julia/v0.4/Blink/src/AtomShell/process.jl:61
 in shell at /home/miki/.julia/v0.4/Blink/src/AtomShell/process.jl:102
 in call at /home/miki/.julia/v0.4/Blink/src/AtomShell/window.jl:37
```
Looking at what's in the directory `/home/miki/.julia/v0.4/Blink/deps/atom/`, I see that there is no `atom` binary there, but there is one named `electron`.

**Comment by rohitvarkey** [comment]
@ackalker Can you try running `Pkg.build("Blink")`?

**Comment by ackalker** [comment]
@rohitvarkey thanks for your advice, but sadly no change in the error:
```julia
julia> Pkg.build("Blink")
INFO: Building HttpParser
INFO: Building MbedTLS
INFO: Building Nettle
INFO: Building Blink
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  386k  100  386k    0     0   411k      0 --:--:-- --:--:-- --:--:--  411k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0   1095      0 --:--:-- --:--:-- --:--:--  1095
100 35.2M  100 35.2M    0     0  2301k      0  0:00:15  0:00:15 --:--:-- 2657k

julia> using Blink
INFO: Recompiling stale cache file /home/miki/.julia/lib/v0.4/HttpParser.ji for module HttpParser.
INFO: Recompiling stale cache file /home/miki/.julia/lib/v0.4/HttpServer.ji for module HttpServer.
INFO: Recompiling stale cache file /home/miki/.julia/lib/v0.4/MbedTLS.ji for module MbedTLS.
INFO: Recompiling stale cache file /home/miki/.julia/lib/v0.4/Nettle.ji for module Nettle.
julia> w = Window()
ERROR: could not spawn `/home/miki/.julia/v0.4/Blink/deps/atom/atom /home/miki/.julia/v0.4/Blink/src/AtomShell/main.js port 6066`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
 in anonymous at process.jl:415
 in setup_stdio at process.jl:403
 in spawn at process.jl:414
 in init at /home/miki/.julia/v0.4/Blink/src/AtomShell/process.jl:61
 in shell at /home/miki/.julia/v0.4/Blink/src/AtomShell/process.jl:102
 in call at /home/miki/.julia/v0.4/Blink/src/AtomShell/window.jl:37
```

**Comment by rohitvarkey** [comment]
Are you on Windows or Linux? [These](https://github.com/JunoLab/Blink.jl/blob/71fd7063396cdcf85e11956561fe826fb10fab67/src/AtomShell/process.jl#L40-L41) lines are probably the issue. Try replacing the path with the one to the electron binary. 

From your above observation about the `electron` binary, I'm guessing you're on Linux, and so the fix should be `deps/atom/atom` ->  `deps/atom/electron`

**Comment by ackalker** [comment]
@rohitvarkey you are right :) I should have mentioned that I'm using Linux. Changing `atom` to `electron` as you suggested makes things work for me.

**Comment by rohitvarkey** [comment]
@ackalker Awesome! Would you like to make a PR with the fix? :smile:

**Comment by spencerlyon2** [comment]
Thanks for working through this. I believe this is fixed by #16 but I haven't started up a Linux box to confirm that the fix there works. @ackalker can you confirm that the change in that pr would work for you?

**Comment by Varanas** [comment]
I think we can merge #16 -- the downloaded zip for linux does indeed include `electron` (but not `atom`) as a binary.

**Comment by spencerlyon2** [comment]
Great let's merge and tag to get this fix as well as the new `Mux` require ino metadata

**Comment by Varanas** [comment]
We might possibly want to wait for some resolution for #20. Although I don't think julia uses `libgit2` on the 0.4 releases (haven't tested yet), so this may not be urgent.

**Comment by rohitvarkey** [comment]
Oh. I missed out on #16! That should fix this.

**Comment by ackalker** [comment]
Thanks all of you for the quick responses, awesome!

**Comment by rohitvarkey** [comment]
I think this can be closed now?

**Comment by spencerlyon2** [comment]
Yes, thanks
