### ISSUE TITLE
loadjs! times out

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#27]
Hi,

I'm in a rush, so this is a placeholder issue and I'll try to add more info later.

I'm getting a timeout when trying to loadjs! d3.js from a CDN. I can see the page has loaded and sits for the 5 seconds and then I get an error, so there must be some problem with the onload callback.

PS: The more I play with Blink, the more I like it, but the lack of examples makes things difficult. Is there someplace Blink is used heavily that I can see it in the wild?

**Comment by EricForgy** [comment]
By the way, I was able to successfully add d3.js by bypassing loadjs! and calling @ js directly:

~~~julia
@js w begin
    d3js = document.createElement("script");
    d3js.src = "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.12/d3.js";
    document.head.appendChild(d3js);
end
~~~

I love @ js! :+1:

**Comment by spencerlyon2** [comment]
Nice, good work figuring it out.

I also had issues using `loadjs!`, but `load!` worked for me. Could you try that?

**Comment by EricForgy** [comment]
Was hopeful, but alas, load! doesn't work for me either :)

It's curious that load! worked for you. Were you loading a .js or .css? It looks like load!  calls loadjs!, so not sure how load! can work if loadjs! doesn't. Hmm...

**Comment by EricForgy** [comment]
Silly me. I was trying to load a JS library to an existing page that did not yet have blink.js loaded. Now I am trying to insert blink.js into existing pages.

https://github.com/JunoLab/Blink.jl/pull/30

**Comment by one-more-minute** [comment]
To answer your second question, there aren't a ton of example uses of Blink.jl right now unfortunately. The only fleshed-out ones I can think of are [DevTools](https://github.com/JunoLab/DevTools.jl) and @spencerlyon2's [Plotlyjs](https://github.com/spencerlyon2/Plotlyjs.jl). If you can think of any small snippets that we could perhaps put in an `examples` folder, they'd be very welcome.
