### ISSUE TITLE
Close a Window

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#28]
Is it possible to programmatically close an open Window?

I see quit(w.shell), but it does not exit gracefully.

**Comment by spencerlyon2** [comment]
```
julia> using Blink

julia> w = Window();

julia> Blink.AtomShell.@dot w close()
```

**Comment by EricForgy** [comment]
Awesome! Thank you @spencerlyon2  :D

**Comment by one-more-minute** [comment]
@EricForgy it'd be great to have a `close` method as part of the exported window API, if you're up for putting a PR together ;)

**Comment by EricForgy** [comment]
@one-more-minute  Sure. Will give it a try :D Since I wrote this, I've been making some progress on understanding how things work. Love this package :D

**Comment by EricForgy** [comment]
Hi @one-more-minute,

I've got the close method in the API now, but wondering what is the best way to proceed. What do you think about PR #35? If you like that, I can combine that with this and make it all just one PR. What do you think?

**Comment by one-more-minute** [comment]
Glad you like it! I haven't managed to take a look at #35 yet but will do so asap. Either way, separate PRs are usually the best way to go.

**Comment by EricForgy** [comment]
Oops. Saw your comment after #36 :D

I'll wait to see what you think of #35. I can submit a separate one just for the "close" if there is some issue with #35.
