### ISSUE TITLE
Extract DOM data and JS variables back to Julia

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#29]
Is there a way to do this?

As a hack, I set the window title to my JS variable using JSON and extract using "title", but I suspect there is a better way :D

**Comment by one-more-minute** [comment]
Yeah, that's quite the hack, isn't it. If you set a global variable `x` in a window `w` you should just be able to grab its value via `@js w x`. As for extracting dom data, I guess you called load a JS library like React which is able to represent the DOM as JSON, then pull the JSON into the Julia side with the usual methods.

**Comment by EricForgy** [comment]
I recently learned the term "web scraper" and I guess I was trying to turn Blink into a web scraping tool, which is too much of an abuse. I may just develop a separate package for web scraping.
