### ISSUE TITLE
Guide to my messy PRs

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#38]
Hi @one-more-minute and @Varanas,

I'm sorry you get to suffer through my learning how to contribute to packages, but Blink happens to be potentially very useful to me so hopefully you can take that as a positive :)

Anyway, I'm afraid I made a mess, so I'll try to organize my PRs here. I'll update this as I go.

As a start, I think #37 is the easiest and, if you agree, can be merged first.

~~~**PR to look at:** #37~~~

Merged. Yay!

**Comment by EricForgy** [comment]
After #37, you can have a look at #35. My first commit on #35 already had the node.js side of #37, but I just stripped that out so #35 only has the blocking code changes.

**Comment by EricForgy** [comment]
Initially in #36, I combined a "close" method (closing #28) with #35, but decided to split the two so I just submitted #39 that just adds a "close" method to the API. Messy. Sorry about that.

**Comment by EricForgy** [comment]
I finished what @GlenHertz started in #21 

**PR to look at:** #40

**Comment by EricForgy** [comment]
With PR #43, loading a URL blocks until the page is loaded. Uses the same idea as #35.

**PR to look at:** #43

**Comment by one-more-minute** [comment]
Haha, no problem, having lots of PRs to deal with is one of the better problems I've had ;) Happy to answer any questions you have as well, it's really great to see people using / contributing to Blink.jl.

**Comment by EricForgy** [comment]
Ok @one-more-minute , @Varanas and @spencerlyon2 

All these PRs are now just down to #43 :)

**Comment by spencerlyon2** [comment]
Great, thanks!
