### ISSUE TITLE
Gadfly plot not opening in Blink window

### ISSUE THREAD

**Issue by EricForgy** [JunoLab/Blink.jl#42]
This following opens the plot in my Chrome browser instead of a Blink window:

![image](https://cloud.githubusercontent.com/assets/8954730/12031264/e0060828-ae44-11e5-846d-43d67e23808c.png)

**Comment by rohitvarkey** [comment]
Could this be https://github.com/JunoLab/Media.jl/issues/3?

**Comment by EricForgy** [comment]
Hi @rohitvarkey ,

Thanks for the reference. It looks like the same issue. What is the appropriate thing to do? Close this issue or leave it for others to see?

**Comment by hustf** [comment]
The appriate thing might be to label the issue as a duplicate, and close it? I hope the last comment on #3 may give an indication of the cause.

**Comment by EricForgy** [comment]
Sure. Thanks @hustf 

Duplicate of https://github.com/JunoLab/Media.jl/issues/3

**Comment by rohitvarkey** [comment]
@EricForgy Could you try and doing a `Pkg.free("Media")` and see if that solves the issue for you? Just to confirm it's actually https://github.com/JunoLab/Media.jl/issues/3.

**Comment by rohitvarkey** [comment]
@EricForgy You'll also need to delete the `Media.ji` file in your `~/.julia/libs/v0.4/` folder.

**Comment by EricForgy** [comment]
:+1: @rohitvarkey  It works now. Thanks.

**Comment by hustf** [comment]
Thank you very much!

I report the below for the sake of completeness. In case somebody would like to add some more code robustness:

1) Cleaned up dirty Media repo, checked out Media 0.1.1+, confirmed Gadfly still does not display as intended.

2) Deleted relevant .ji files, deleted Devtools and cloned it again.

3)
````
julia> using Gadfly
INFO: Precompiling module Gadfly...

julia> Pkg.free("Media")
INFO: Freeing Media
INFO: No packages to install, update or remove

julia> using DevTools

WARNING: deprecated syntax "media (" at C:\Users\F\.julia\v0.4\Media\src\system.jl:35.
Use "media(" instead.

julia> plot(x=1:100, y= cumsum(rand(100)-0.5),Geom.line)

Electron server listening on port 7434
Error showing value of type Gadfly.Plot:
ERROR: Callback timed out
 in yieldto at task.jl:71
 in wait at task.jl:371
 in wait at task.jl:286
 in wait at C:\Users\F\.julia\v0.4\Blink\src\rpc\callbacks.jl:8
 in js at C:\Users\F\.julia\v0.4\Blink\src\rpc/rpc.jl:28
 in call at C:\Users\F\.julia\v0.4\Blink\src\AtomShell\window.jl:27
 [inlined code] from C:\Users\F\.julia\v0.4\Lazy\src\macros.jl:161
 in render at C:\Users\F\.julia\v0.4\DevTools\src\display\display.jl:33
 in display at C:\Users\F\.julia\v0.4\Media\src\compat.jl:9
 [inlined code] from multimedia.jl:151
 in display at C:\Users\F\.julia\v0.4\Gadfly\src\Gadfly.jl:922
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at LineEdit.jl:1610
 in run_frontend at REPL.jl:863
 in run_repl at REPL.jl:167
 in _start at client.jl:420

````

(This opens a Chrome window with caption Julia and the text Not found)

4) 
Without closing the window:
````
plot(x=1:100, y= cumsum(rand(100)-0.5),Geom.line)
````

Voila! A second Chrome window opens with the nice plot. For the record: Windows 10 64 bit and it works with:

````
julia> Pkg.status("Media")
 - Media                         0.1.1
julia> Pkg.status("Blink")
 - Blink                         0.2.1+             master
julia> Pkg.status("DevTools")
 - DevTools                      0.0.0-             master (unregistered)
````
