### ISSUE TITLE
Breaks show for some simple primitives like integer tuples

### ISSUE THREAD

**Issue by jasonmorton** [JunoLab/Blink.jl#5]
At a new prompt, 
```julia
import Blink
(3,3)
```
gives an error:
ERROR: `super` has no method matching super(::Type{(Int64,Int64)})
 in distance at /home/jason/.julia/v0.3/Blink/src/graphics/system.jl:7
 in nearest at /home/jason/.julia/v0.3/Blink/src/graphics/system.jl:12
 in anonymous at /home/jason/.julia/v0.3/Blink/src/graphics/system.jl:16
 in _mapreduce at reduce.jl:166
 in mapreduce at reduce.jl:182
 in nearest at /home/jason/.julia/v0.3/Blink/src/graphics/system.jl:15
 in getdisplay at /home/jason/.julia/v0.3/Blink/src/graphics/system.jl:102
 in display at /home/jason/.julia/v0.3/Blink/src/graphics/compat.jl:9
 in display at multimedia.jl:149
 in print_response at REPL.jl:139
 in print_response at REPL.jl:124
 in anonymous at REPL.jl:586
 in run_interface at ./LineEdit.jl:1379
 in run_frontend at ./REPL.jl:818
 in run_repl at ./REPL.jl:169
 in _start at ./client.jl:400

**Comment by EricForgy** [comment]
Hi @jasonmorton ,

Is this still an issue for you? It seems to work for me now. Just curious.

![image](https://cloud.githubusercontent.com/assets/8954730/12031040/486e788a-ae42-11e5-97cf-1aa99c0f99f7.png)

**Comment by jasonmorton** [comment]
Still an issue with Julia 0.3.8. In 0.4.2, the build of Blink is failing because of dependency MbedTLS failing for me.  I'll update if I get it working.
