### ISSUE TITLE
Blink asks for firewall permissions on startup

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Blink.jl#66]
See e.g. [here](http://discuss.junolab.org/t/atom-jl-keeps-asking-for-firewall-permission-os-x/905).

Not quite sure where that happens or if it's even necessary -- if it is, then maybe defer asking until runtime or something?

**Comment by MikeInnes** [comment]
The repeated permissions are probably due to us randomising the port. You fixed this in Juno at one point by listening only on localhost, right? We should be able to do the same thing here.
