### ISSUE TITLE
Get 'nothing' from @js after loadhtml on a window 

### ISSUE THREAD

**Issue by CVasquezG** [JunoLab/Blink.jl#72]
I am having trouble getting data back the document back to Julia.
This is the code that I have:
```

using Blink
w = Window()
@js w console.log("Hello from julia") #working
loadhtml(w,
"<script>
var x = 10
</script>
<h1 id='title'>TITLE $hi</h1>
")
@js w  document.getElementById("title").innerHTML = "Changed" #working
println(@js w Math.log(10)) #prints 'nothing'
println(@js w x) #prints 'nothing'
println(title(w)) #working
readline(STDIN)
```
I am missing something? or is there no way to get back values back to julia from the document?

**Comment by pfitzseb** [comment]
When you call `loadhtml`, you'll replace the entire contents of that electron window, which means the communiation will be borked. It should be possible to work around that (basically need to establish a new connection by using [blink.js](https://github.com/JunoLab/Blink.jl/blob/master/res/blink.js)), but I don't really know how to do that.

Also have a look at [this](https://github.com/JunoLab/Blink.jl/blob/60e39641ffb8b3524fca71ec5c0cde4c850fc239/src/content/api.jl); in particular, `body!` is much easier to use than `loadhtml`.

**Comment by CVasquezG** [comment]
Thanks for the explanation, using body! fixed my problem.
