### ISSUE TITLE
Is there a way to add files (.js, .css,  .jpg, ect...) to a window sources?

### ISSUE THREAD

**Issue by CVasquezG** [JunoLab/Blink.jl#73]
How would I be able to add files to a window, because right now for all my javascript is in a big string that i send to the window using body!. But its getting really long and its pretty hard to work with. I also wanted to add pics but i have no idea where they need to be stored so that the window can access them.

I figured there must be a way to send files kind of like how blink.js , blink.css etc... are in the window source files.
![image](https://cloud.githubusercontent.com/assets/8881142/19839036/629dc8f4-9e98-11e6-8e29-9c370d70edf2.png)

When i do openfile it just overwrites everything.

Also another issue I have right now is that is i haven't found a way to run a js script in a julia file that requires a space  like `@js w x = 10`  or create a new var `@js w var y  = 2`.  Its not a big issue since i have found workarounds but i would like to know if this is possible.

Thanks

**Comment by pfitzseb** [comment]
[`load!`](https://github.com/JunoLab/Blink.jl/blob/master/src/content/api.jl#L56) should work for that. Also have a look at the functions above that for how to write js inline.
