### ISSUE TITLE
using Blink    ==>    ERROR: namify not defined

### ISSUE THREAD

**Issue by semmottos** [JunoLab/Blink.jl#8]
Things must have changed in some of the needed packages because I have reinstalled the Julia app from the same dmg I've been using for a while now. Here's the haeadache on a clean slate:

Last login: Tue Aug 25 21:05:24 on ttys001
Jussis-Air:~ IsoPomo$ exec '/Applications/Julia-0.3.11.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
 _/ |\__'_|_|_|__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.status()
INFO: Initializing package repository /Users/IsoPomo/.julia/v0.3
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
No packages installed

julia> Pkg.resolve()
INFO: No packages to install, update or remove

julia> Pkg.add("Blink")
INFO: Cloning cache of Blink from git://github.com/JunoLab/Blink.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of Lazy from git://github.com/one-more-minute/Lazy.jl.git
INFO: Cloning cache of MacroTools from git://github.com/one-more-minute/MacroTools.jl.git
INFO: Cloning cache of Requires from git://github.com/one-more-minute/Requires.jl.git
INFO: Installing Blink v0.1.4
INFO: Installing Compat v0.6.0
INFO: Installing JSON v0.4.5
INFO: Installing Lazy v0.10.0
INFO: Installing MacroTools v0.2.0
INFO: Installing Requires v0.1.3
INFO: Building Blink
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100k  100  100k    0     0  86062      0  0:00:01  0:00:01 --:--:-- 86155
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35.8M  100 35.8M    0     0   839k      0  0:00:43  0:00:43 --:--:--  974k
Archive:  atom-shell-mac-0.20.3.zip
   creating: Julia.app/
   creating: Julia.app/Contents/
   creating: Julia.app/Contents/Frameworks/
   creating: Julia.app/Contents/Frameworks/Julia Framework.framework/
    linking: Julia.app/Contents/Frameworks/Julia Framework.framework/Frameworks  -> Versions/Current/Frameworks 
    linking: Julia.app/Contents/Frameworks/Julia Framework.framework/Julia Framework  -> Versions/Current/Julia Framework 
    linking: Julia.app/Contents/Frameworks/Julia Framework.framework/Libraries  -> Versions/Current/Libraries 
    linking: Julia.app/Contents/Frameworks/Julia Framework.framework/Resources  -> Versions/Current/Resources 
   creating: Julia.app/Contents/Frameworks/Julia Framework.framework/Versions/
   creating: Julia.app/Contents/Frameworks/Julia Framework.framework/Versions/A/
  inflating: Julia.app/Contents/Frameworks/Julia Framework.framework/Versions/A/Julia Framework  
=====================>   260 lines removed   <==========================
   creating: Julia.app/Contents/Resources/vi.lproj/
   creating: Julia.app/Contents/Resources/zh_CN.lproj/
   creating: Julia.app/Contents/Resources/zh_TW.lproj/
finishing deferred symbolic links:
  Julia.app/Contents/Frameworks/Julia Framework.framework/Frameworks -> Versions/Current/Frameworks
  Julia.app/Contents/Frameworks/Julia Framework.framework/Julia Framework -> Versions/Current/Julia Framework
  Julia.app/Contents/Frameworks/Julia Framework.framework/Libraries -> Versions/Current/Libraries
  Julia.app/Contents/Frameworks/Julia Framework.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Julia Framework.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/Mantle.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/Mantle.framework/Mantle -> Versions/Current/Mantle
  Julia.app/Contents/Frameworks/Mantle.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Mantle.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/ReactiveCocoa -> Versions/Current/ReactiveCocoa
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/Squirrel.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/Squirrel.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Squirrel.framework/Squirrel -> Versions/Current/Squirrel
  Julia.app/Contents/Frameworks/Squirrel.framework/Versions/Current -> A
INFO: Package database updated

julia> using Blink
ERROR: namify not defined
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/IsoPomo/.julia/v0.3/Blink/src/graphics/system.jl, in expression starting on line 51
while loading /Users/IsoPomo/.julia/v0.3/Blink/src/graphics/Graphics.jl, in expression starting on line 3
while loading /Users/IsoPomo/.julia/v0.3/Blink/src/Blink.jl, in expression starting on line 1

julia> Pkg.status()
1 required packages:
- Blink                         0.1.4
  5 additional packages:
- Compat                        0.6.0
- JSON                          0.4.5
- Lazy                          0.10.0
- MacroTools                    0.2.0
- Requires                      0.1.3

julia>

**Comment by one-more-minute** [comment]
Ok, I tagged a new release, v0.1.5, which should fix this for you. Let me know if it does the trick!

**Comment by semmottos** [comment]
Hi!

1. Blink installs and works in Julia v0.3 without a glitch.

2. In Julia v0.4 I get a warning from the 'using Blink' statement but I still can use Blink successfully. Here's an excerpt from the install&using:

Jussis-MacBook-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0-pre-f1e6442b6f.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7090 (2015-08-29 00:28 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f1e6442 (2 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.status()
INFO: Initializing package repository /Users/IsoPomo/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
No packages installed

julia> Pkg.add("Blink")
INFO: Installing Blink v0.1.5
INFO: Installing Compat v0.6.0
INFO: Installing JSON v0.4.5
INFO: Installing Lazy v0.10.0
INFO: Installing MacroTools v0.2.0
INFO: Installing Requires v0.1.3
INFO: Building Blink
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100k  100  100k    0     0   118k      0 --:--:-- --:--:-- --:--:--  118k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35.8M  100 35.8M    0     0   966k      0  0:00:37  0:00:37 --:--:--  997k
Archive:  atom-shell-mac-0.20.3.zip
   creating: Julia.app/
   creating: Julia.app/Contents/
   creating: Julia.app/Contents/Frameworks/
   creating: Julia.app/Contents/Frameworks/Julia Framework.framework/
 
 =========================================================================
 LOTS AND LOTS OF LINES REMOVED
 =========================================================================
   
   creating: Julia.app/Contents/Resources/te.lproj/
   creating: Julia.app/Contents/Resources/th.lproj/
   creating: Julia.app/Contents/Resources/tr.lproj/
   creating: Julia.app/Contents/Resources/uk.lproj/
   creating: Julia.app/Contents/Resources/vi.lproj/
   creating: Julia.app/Contents/Resources/zh_CN.lproj/
   creating: Julia.app/Contents/Resources/zh_TW.lproj/
finishing deferred symbolic links:
  Julia.app/Contents/Frameworks/Julia Framework.framework/Frameworks -> Versions/Current/Frameworks
  Julia.app/Contents/Frameworks/Julia Framework.framework/Julia Framework -> Versions/Current/Julia Framework
  Julia.app/Contents/Frameworks/Julia Framework.framework/Libraries -> Versions/Current/Libraries
  Julia.app/Contents/Frameworks/Julia Framework.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Julia Framework.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/Mantle.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/Mantle.framework/Mantle -> Versions/Current/Mantle
  Julia.app/Contents/Frameworks/Mantle.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Mantle.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/ReactiveCocoa -> Versions/Current/ReactiveCocoa
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current -> A
  Julia.app/Contents/Frameworks/Squirrel.framework/Headers -> Versions/Current/Headers
  Julia.app/Contents/Frameworks/Squirrel.framework/Resources -> Versions/Current/Resources
  Julia.app/Contents/Frameworks/Squirrel.framework/Squirrel -> Versions/Current/Squirrel
  Julia.app/Contents/Frameworks/Squirrel.framework/Versions/Current -> A
INFO: Package database updated

julia> using Blink
INFO: Precompiling module Compat...
WARNING: New definition 
    size(Blink.Window, Any, Any) at /Users/IsoPomo/.julia/v0.4/Blink/src/window.jl:68
is ambiguous with: 
    size(Any, Integer, Integer, Integer...) at abstractarray.jl:54.
To fix, define 
    size(Blink.Window, Integer, Integer)
before the new definition.

julia> 

===================================================================

BTW 1. I already use Blink in 3 separate programs:

1 The one which acts as a vocabulary trainer

2. A program that I use to enter tags to some of the words  in the 80000 word data base to mark them as words that that I have encountered somewhere in the Internet, heard somewhere etc:
![image](https://cloud.githubusercontent.com/assets/6031748/9583026/a55ab9bc-5011-11e5-9e87-43d4dd923489.png)
 Here I use Blink (and Trie from DataStructures) to show which are possible words in the DB that start like the letters that I have entered. As soon as there is at most 9 candidates they are shown and the numbers attached to them can be given as a shortcut keys to select the one I wish to enter. When the selection is made the program shows the Google translation for it so that I can make sure this is what I really want to enter and to have a possibility to study the examples also i.e. to learn the usage of the word also. After that I can either skip or accept the tagging of the word.

3. I also have a program to make ad hoc queries to the data base and show the results in a Blink window. Because SQLite gives me the names of the columns the code is completely general. Here's one query result to show what are those monsters for words that are at least 25 characters long:

![image](https://cloud.githubusercontent.com/assets/6031748/9583297/3a033854-5013-11e5-816e-68266ba34ae2.png)

These use cases are just the top of the iceberg of the possibilities of using Blink, I think.

===================================================================


BTW 2. I've installed and used a little your atom-julia-client and it looks good. I was lucky to have found a reference to it because it's time for me to get serious with Julia. I've only scratched the surface by skipping lot's of the documentation and still been able to do useful work. Getting serious means starting to read the v0.4 documentation and doing experiments with the atom-julia-client. I wouldn't be surprised if  you'll be hearing from me again.

**Comment by semmottos** [comment]
Oh well, I didn't succeed in including the png's. Here's another try and if that's not going to work I give up, the pics are not that important anyway!

![screen shot 2015-08-31 at 10 07 37](https://cloud.githubusercontent.com/assets/6031748/9583599/11398fa2-5015-11e5-8e98-8c07892975bf.png)


![screen shot 2015-08-31 at 10 55 43](https://cloud.githubusercontent.com/assets/6031748/9583665/6af7ee12-5015-11e5-9b68-36f47eb6768e.png)

**Comment by shashi** [comment]
It looks like the errors are just warnings... Have you doing more anyway?

**Comment by semmottos** [comment]
I'm doing fine now with Blink and Gadfly peacefully coexisting. It's just
hard for a Julia beginner to know that a line labeled ERROR: and displayed
in red is not so serious anyway. Knowing more of Julia would help in
separating the different levels of severity but I'm getting there,
hopefully.

Thanks for commenting!
