### ISSUE TITLE
Julia 0.5.1 on CentOS 6.5: Blink does not open a new window

### ISSUE THREAD

**Issue by fasiha** [JunoLab/Blink.jl#82]
First ran into this problem with PlotlyJS.jl, but narrowed it down to Blink. I’m trying to get Blink/PlotlyJS working on CentOS 6.5 (released late 2013, so very old… don’t ask why I’m using this old distro), with Software Collections’ [devtoolset-3](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/) installed. I’m running this inside a VirtualBox VM.

Instead of opening a new window, `Window()` experiences ECONNREFUSED:

```
[fasih@localhost bin]$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using Blink

julia> w  = Window()
ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto(::Task, ::ANY) at ./event.jl:136
 in wait() at ./event.jl:169
 in wait(::Condition) at ./event.jl:27
 in stream_wait(::TCPSocket, ::Condition, ::Vararg{Condition,N}) at ./stream.jl:44
 in wait_connected(::TCPSocket) at ./stream.jl:265
 in connect at ./stream.jl:960 [inlined]
 in connect(::IPv4, ::Int64) at ./socket.jl:677
 in #try_connect#4(::Float64, ::Int64, ::Function, ::IPv4, ::Vararg{Any,N}) at /home/fasih/.julia/v0.5/Blink/src/AtomShell/process.jl:62
 in #init#5(::Bool, ::Function) at /home/fasih/.julia/v0.5/Blink/src/AtomShell/process.jl:76
 in (::Blink.AtomShell.#kw##init)(::Array{Any,1}, ::Blink.AtomShell.#init) at ./<missing>:0
 in #shell#8(::Bool, ::Function) at /home/fasih/.julia/v0.5/Blink/src/AtomShell/process.jl:114
 in Blink.AtomShell.Window() at /home/fasih/.julia/v0.5/Blink/src/AtomShell/window.jl:37
```

Could the fact that I’m inside a VM be affecting anything? I’m using NAT to get network access in the VM, so I don’t think it’s a connectivity issue.

**Comment by fasiha** [comment]
Same error as reported in http://pkg.julialang.org/logs/Blink_0.5.log ?

**Comment by sglyon** [comment]
Hey @fasiha I do think the issue is with running inside of a VM.

This has been reported a few times: [here](https://github.com/sglyon/PlotlyJS.jl/issues/33#issuecomment-280460385) and [here](https://github.com/JunoLab/Blink.jl/issues/76).

I don't think anyone has come up with a workable solution yet. If you do happen to find a fix please let us know so we can help others.

**Comment by fasiha** [comment]
Thanks @sglyon, and sorry for opening a new issue without properly searching for the others!

**Comment by sglyon** [comment]
No problem, I didn't mean to sound blunt.

I just wanted to point you to where discussion has taken place in case comments there can help you.

good luck

**Comment by fasiha** [comment]
Oh, not blunt at all, on the contrary, thank you for your kindness—and for your hard work on Blink and PlotlyJS 🙇! I told my colleagues, “PlotlyJS is so great, I am *not* going to install PyPlot on this ancient CentOS box—I will drag you kicking and screaming into the 21st century” but alas… 😂.

**Comment by krcools** [comment]
As reported earlier at PlotlyJS.jl, I see this error on a machine I am pretty sure is not virtual. It is not solved by using `run-xvfb`.

**Comment by Cody-G** [comment]
I'm also getting this on a laptop running Ubuntu 17.10 on bare metal.

**Comment by timholy** [comment]
As suggested [here](https://github.com/sglyon/PlotlyJS.jl/issues/33#issuecomment-355384643) `Blink.AtomShell.install()`solved the connection error for me.

But PlotlyJS still doesn't produce anything (the animation that I interpret as "initializing" or "waiting for input" never disappears). I haven't figured out how to fix that.
