### ISSUE TITLE
Julia v0.4, Blink 0.1.5, Gadfly 0.3.14: odd interference of 'using Gadfly' with 'using Blink'

### ISSUE THREAD

**Issue by semmottos** [JunoLab/Blink.jl#9]
Changing the order of the 'using' lines for Blink and Gadfly can cause odd effects. The last example is
the order I'm using. Using this order both Gadfly and Blink work, at least at the level that I
have been using them up till now. I don't know if this is an issue of Julia, Gadfly, Blink or some other package but I report it here to start with.

using Blink
using Gadfly

sequence can produce this output´: 

Jussis-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7113 (2015-08-31 17:47 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 092bcf4 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Blink
WARNING: New definition 
    size(Blink.Window, Any, Any) at /Users/IsoPomo/.julia/v0.4/Blink/src/window.jl:68
is ambiguous with: 
    size(Any, Integer, Integer, Integer...) at abstractarray.jl:54.
To fix, define 
    size(Blink.Window, Integer, Integer)
before the new definition.

julia> using Gadfly
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: Module Graphics uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji
INFO: Precompiling module Cairo...
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: Module Graphics uuid did not match cache file
ERROR: **precompile**(true) but require failed to create a precompiled cache file
 in require at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:400
 in recompile_stale at loading.jl:418
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib

julia> 

using Blink
using Gadfly
but this can sometimes also produce this: 

Jussis-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7113 (2015-08-31 17:47 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 092bcf4 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Blink
WARNING: New definition 
    size(Blink.Window, Any, Any) at /Users/IsoPomo/.julia/v0.4/Blink/src/window.jl:68
is ambiguous with: 
    size(Any, Integer, Integer, Integer...) at abstractarray.jl:54.
To fix, define 
    size(Blink.Window, Integer, Integer)
before the new definition.

julia> using Gadfly
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Compose.ji for module Compose.
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at deprecated.jl:73
 in require at deprecated.jl:659
 in isinstalled at /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl:34
 in include at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at no file:2
 in process_options at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 144
WARNING: Module Graphics uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /Users/IsoPomo/.julia/lib/v0.4/Compose.ji
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: Module Graphics uuid did not match cache file
WARNING: deserialization checks failed while attempting to load cache from /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji
INFO: Precompiling module Cairo...
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: Module Graphics uuid did not match cache file
ERROR: LoadError: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in stale_cachefile at loading.jl:400
 in recompile_stale at loading.jl:418
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/IsoPomo/.julia/v0.4/Compose/src/cairo_backends.jl, in expression starting on line 4
while loading /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 132

julia> 

using Gadfly
using Blink

can cause this to be produced:

Jussis-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7113 (2015-08-31 17:47 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 092bcf4 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Gadfly
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Compose.ji for module Compose.
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at deprecated.jl:73
 in require at deprecated.jl:659
 in isinstalled at /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl:34
 in include at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at no file:2
 in process_options at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl, in expression starting on line 144
INFO: Recompiling stale cache file /Users/IsoPomo/.julia/lib/v0.4/Gadfly.ji for module Gadfly.
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at deprecated.jl:73
 in require at deprecated.jl:659
 in isinstalled at /Users/IsoPomo/.julia/v0.4/Compose/src/Compose.jl:34
 in include at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at no file:2
 in process_options at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/IsoPomo/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 933

julia> using Blink
WARNING: replacing module Graphics
WARNING: New definition 
    size(Blink.Window, Any, Any) at /Users/IsoPomo/.julia/v0.4/Blink/src/window.jl:68
is ambiguous with: 
    size(Any, Integer, Integer, Integer...) at abstractarray.jl:54.
To fix, define 
    size(Blink.Window, Integer, Integer)
before the new definition.

julia> 

using Gadfly
using Blink

 or this (this is I think the stationary state when using this order repeteadly and this is the order in which things work):

exec '/Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/bin/julia'
Jussis-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0-pre-092bcf4604.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7113 (2015-08-31 17:47 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit 092bcf4 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Gadfly

julia> using Blink
WARNING: replacing module Graphics
WARNING: using Graphics.render in module Main conflicts with an existing identifier.
WARNING: New definition 
    size(Blink.Window, Any, Any) at /Users/IsoPomo/.julia/v0.4/Blink/src/window.jl:68
is ambiguous with: 
    size(Any, Integer, Integer, Integer...) at abstractarray.jl:54.
To fix, define 
    size(Blink.Window, Integer, Integer)
before the new definition.

julia>

**Comment by yuyichao** [comment]
It's very hard to see what's happening without quoting the code. The uuid mismatch error is https://github.com/JuliaLang/julia/issues/13200.
