### ISSUE TITLE
Websocket error after loading a URL

### ISSUE THREAD

**Issue by nicknack23** [JunoLab/Blink.jl#92]
The first README example no longer works:
```
using Blink
w = Window()
body!(w, "Hello World")
@js w Math.log(10)
```
Results in `2.302585092994046`, so far everything is fine. However, although `loadurl(w, "http://julialang.org")` displays the page as it should, you get an error in the REPL:
```
Error handling websocket connection:
Error: client disconnected
```
Trying `@js w Math.log(10)` once again after loading a URL no longer gives a result. This is in Julia 0.6 on Windows 10.

**Comment by pfitzseb** [comment]
Seems to be fixed on master (and/or 0.6).
