### ISSUE TITLE
Upgrade to latest stable version of Electron

### ISSUE THREAD

**Issue by nicknack23** [JunoLab/Blink.jl#93]
Currently Blink installs version 0.35.2 of Electron which was released in 2015. The current stable release is 1.7.6. If my count is correct that means we're 98 releases behind. It's beginning to feel like running Netscape Navigator (not to knock NN, it was awesome back in 1995).  :)

**Comment by Nectarineimp** [comment]
I am unable to use Plotly(JS) or Plots (when using plotlyjs as a backend) to show 3D visualizations because it is so ancient. I have up to date drivers, I have a new machine, it checks out on webgl and electron latest releases.

Example test:
```
using Plotly
p = plot(rand(10, 2), kind=:scattergl) #fails, uses WebGL
p = plot(rand(10, 2), kind=:scatter) #works like a charm, does not use WebGL
```

**Comment by pfitzseb** [comment]
See #97.

**Comment by pfitzseb** [comment]
Done. Would be awesome if you could `Pkg.checkout` Blink and report how it goes.
