### ISSUE TITLE
build.jl

### ISSUE THREAD

**Issue by davidanthoff** [JunoLab/Blink.jl#99]
Is there a reason why ``Blink.AtomShell.install()`` isn't just called in a ``build.jl`` file?

**Comment by sglyon** [comment]
I think the reason is that if you are only using Juno, Blink.jl will use the election inside Atom and no additional electron will ever need to be downloaded.

**Comment by davidanthoff** [comment]
Ah, I see... Well, I guess I can just put a call to ``install()`` into a ``build.jl`` file in the package where I want to use this...

Actually, what I'm playing around with is https://github.com/davidanthoff/BlinkDisplay.jl. My idea is to essentially take some mix of what you have in PlotlyJS.jl and what DevTools.jl had, but base it all on the normal julia multimedia API as a generic figure viewer that works with any source that plugs into the julia multimedia API. We have a really generic plot pane in VS Code that just works via the julia multimedia API, and it should be pretty straightforward to get the same working with a blink based UI, I think. Ok if I contact you with a question if I run into a problem? Maybe this could eventually even work for Plotlyjs.jl?

**Comment by sglyon** [comment]
Sounds exciting!

For sure. Feel free to reach out. Fixing the display system for PlotlyJS has long been on the todo list (unfortunately too low to actually get done ...)
